name: Build TypeScript
'on':
  push:
    branches:
      - '2.0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Get version from package.json
        id: get_version
        run: >
          echo "::set-output name=VERSION::$(node -e
          "console.log(require('./package.json').version)")"
      - name: 'Build, Commit and push changes'
        run: |
          git config --local user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_CONFIG_USERNAME }}"
          git fetch origin release_2.0
          git checkout release_2.0
          git checkout 2.0 -- "."
          git checkout release_2.0 -- ".gitignore"
          yarn build
          git reset "src/*.ts"
          git rm -rf .github/workflows/compile-typescript.yaml
          git add -A
          git commit -m "Stable V${{ steps.get_version.outputs.VERSION }}"
          git push origin release_2.0
